services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    # buildCommand: pip install -r requirements.txt
    buildCommand: poetry install
    startCommand: uvicorn src/api/main:app --host 0.0.0.0 --port $PORT