services:
  # A Docker web service
  - type: web
    name: slice-of-mercury-fastapi
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install
    startCommand: poetry run start_server